Small stu2 issues
HL7/fhircast-docs pull request #336
Opened 2020-10-26 17:58 UTC by isaacvetter

2020-10-26 21:27 UTC, wmaethner approved these changes

2020-10-27 12:57 UTC, NiklasSvenzen commented on docs/syncconsiderations.md
> +Once an app is launched with initial context, for example, the currently in context patient, the app must subscribe before it receives notifications of updated context. Between the instant of launch
liklihood -> likelihood

2020-10-27 12:58 UTC, NiklasSvenzen requested changes
Looks good, except typo likelihood

2020-10-27 13:14 UTC, isaacvetter commented on docs/syncconsiderations.md
> +Once an app is launched with initial context, for example, the currently in context patient, the app must subscribe before it receives notifications of updated context. Between the instant of launch
```suggestion
Once an app is launched with initial context, for example, the currently in context patient, the app must subscribe before it receives notifications of updated context. Between the instant of launch and the instant of a confirmed subscription, it's technically possible for context to change, such that the newly launched app joins a session with stale contextual information. In most scenarios, this problem is likely noticeable by the end user. Apps should optimize the time required to launch and subscribe to reduce this likelihood.
```

2020-11-02 20:32 UTC, merged