JIRA 36908
HL7/fhircast-docs pull request #478
Opened 2023-03-14 19:19 UTC by EricOnFHIR

Added text explaining which parts of the implementation guide are normative and which are informative.  Ensured no normative VERBs are used in informative text.

Also aligned the FHIR Subscription relationship text with that in FHIR Subscription.

2023-03-15 07:32 UTC, bvdh requested changes

2023-03-15 07:32 UTC, bvdh commented on input/pagecontent/5_glossary.md
Not sure that also applies to this section as the definitions here are used in mandatory text.

2023-03-15 07:32 UTC, bvdh commented on input/pagecontent/6_change-log.md
Prevent duplication. We state the same in the intro, no need to repeat it here.

2023-03-15 15:41 UTC, EricOnFHIR commented on input/pagecontent/5_glossary.md
Changes made as requested.

2023-03-21 13:29 UTC, bvdh approved these changes

2023-03-21 13:29 UTC, merged