Add Constraints to Ensure a Business Identifier
HL7/fhircast-docs pull request #493
Opened 2023-08-16 16:56 UTC by EricOnFHIR

Enhancement to PR#492: FHIR 40658 Contextual Subject Profiles

2023-08-23 13:00 UTC, bvdh requested changes

2023-08-23 13:00 UTC, bvdh commented on input/fsh/FHIRcastDiagnosticReportOpen.fsh
**FHIR R4 versus FHIR R5**
In the FHIR R4 DiagnosticReport resource image study references would be placed in the `imagingStudy` attribute.  In a FHIR R5 (or above) DiagnosticReport this attribute has been renamed `study` since the allowed reference types has been expanded to include references to GenomicStudy resources.  This is obviously a breaking change.

In FHIRcast deployments based on FHIR R5, the attribute `study` SHALL be used rather than the `imagingStudy` attribute.

Additionally FHIR R5 includes a `supportingInfo` attribute.  While not yet formally provided for in FHIR R5, it has been recommended that the next release of FHIR allow an ImagingStudy reference be included in this attribute so that the DiagnosticReport could indicate one or more image studies were consulted during the creation of the report. As such in FHIR R5 deployments, this field is considered labeled as must support.

2023-08-24 14:57 UTC, EricOnFHIR commented on input/fsh/FHIRcastDiagnosticReportClose.fsh
> +The accession number of the order which directly or in directly triggered the report to be created SHOULD be included as a business identifier if it is known.  The accession number is stored as Refer
The discussion was in a -close we loosen identifiers to SHOULD  - of course the resource id is a SHALL and SHALL match that in the corresponding -open.  You are also thinking the -close **must** contain the identifiers provided in the corresponding -open?

2023-08-25 06:56 UTC, bvdh commented on input/fsh/FHIRcastDiagnosticReportClose.fsh
> +The accession number of the order which directly or in directly triggered the report to be created SHOULD be included as a business identifier if it is known.  The accession number is stored as Refer
That is a separate discussion. In theory, the close only requires the id as it does not mean much to an application that did not receive the corresponding -open. From that point of view, a -close is not required to include them.

2023-08-25 07:01 UTC, bvdh approved these changes

2023-08-25 07:02 UTC, merged