Fhir 40566 - add event and FHIR version support
HL7/fhircast-docs pull request #500
Opened 2023-09-28 07:42 UTC by bvdh

2023-10-11 13:06 UTC, EricOnFHIR requested changes

2023-10-11 13:06 UTC, EricOnFHIR commented on input/pagecontent/2-3-Events.md
> +The `FHIRresource` indicates the focus of the event. The next part defines the type of event. The optional `Version` field allows specifying the version of the event. When this field is omitted, it r
When the `Version` field is present it SHALL be a code from the [FHIR-version](https://hl7.org/fhir/valueset-FHIR-version.html) value set.

2023-10-11 13:06 UTC, EricOnFHIR commented on input/pagecontent/3-2-1-SyncError.md
> +| Version | 1.1
I would like to understand the purpose of the `Version` field

2023-10-18 12:01 UTC, bvdh commented on input/pagecontent/2-3-Events.md
> +The `FHIRresource` indicates the focus of the event. The next part defines the type of event. The optional `Version` field allows specifying the version of the event. When this field is omitted, it r
Agreed on the first comment. The second one relates to the FHIR-version which is a different topic that is addressed in Conformance

2024-07-04 07:39 UTC, closed without merging

2024-07-04 07:40 UTC, bvdh commented
replaced by https://github.com/HL7/fhircast-docs/pull/585 - to facilitate easier merging