Content by reference
HL7/fhircast-docs pull request #548
Opened 2024-03-29 16:00 UTC by LYTrent

Fix for this jira https://jira.hl7.org/browse/FHIR-36911

Hey Isaac,

Not sure if this completely address this jira. Thoughts? Maybe also deleting 2-10-2?

2024-03-29 21:25 UTC, isaacvetter commented
Hey Trent,

yeah, this one is kind of tricky. It might make sense to ask Bas for help. I think a partial list of files to be edited include:
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/artifacts.html -- remove Subcribe to container examples
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/2-10-2-ContentSharingFHIR.html -- all
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/2-10-ContentSharing.html - references to 2-10-2, which calls into question if this entire page should also be removed. 
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/4-7-hybrid-content-sharing.html -- all
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/SubscriptionTopic-container-update-topic.html -- all
- https://build.fhir.org/ig/HL7/fhircast-docs/branches/LYTrent-patch-7/SubscriptionTopic-container-update-resource.html - all
- 
-

2024-04-01 14:22 UTC, EricOnFHIR requested changes
I added the reference FHIR transaction bundle as discussed in the FHIRcast meeting of 1-April-2024.

2024-04-01 14:48 UTC, isaacvetter approved these changes

2024-04-01 14:48 UTC, isaacvetter commented on input/pagecontent/2-10-1-ContentSharingFHIRcastMessaging.md
> +Commonly all information relevant to the update is contained in an entry’s resource (i.e., information is passed by value). For example, an `Observation` resource usually contains all information reg
```suggestion
The [FHIR transaction interaction](http://hl7.org/fhir/http.html#transaction) defines how multiple actions can be grouped together and performed as one, such that all information being created or updated is contained in an entry’s resource (i.e., information is passed by value). For example, an `Observation` resource usually contains all relevant information regarding that observation. While it is possible to communicate content by reference even within a transaction bundle, implementer experimentation is needed for increased use of references to resources not contained in the `Bundle`.  
```

2024-04-01 14:55 UTC, merged