Home-open event updates and links across events and multitab pages
HL7/fhircast-docs pull request #583
Opened 2024-06-21 15:38 UTC by TimothyKopec

https://jira.hl7.org/browse/FHIR-41178

2024-07-02 22:07 UTC, isaacvetter commented on input/pagecontent/4-4-multitab-considerations.md
>  Since we are inherently representing the lack of context, the event will not fully conform to the defined event naming syntax and will instead use a static name (similar to `UserLogout.html`).
The [Home-open event](3-2-5-Home-open.html) represents a lack of context.

2024-07-02 22:08 UTC, isaacvetter requested changes

2024-07-02 22:08 UTC, isaacvetter commented on input/pagecontent/4-4-multitab-considerations.md
>  Since we are inherently representing the lack of context, the event will not fully conform to the defined event naming syntax and will instead use a static name (similar to `UserLogout.html`).
```suggestion
The [Home-open event](3-2-5-Home-open.html) represents a lack of context.
```

2024-07-03 09:07 UTC, bvdh commented
I've added some text improvements, added a comment that the event does not change current context

2024-12-31 15:18 UTC, isaacvetter commented on input/pagecontent/3-2-5-Home-open.md
> +Note that sending a `Home-open` event merely signals that an application has switched to the no-context tab. It does not change the current context. For instance, if a specific patient is currently i
```suggestion
```

2024-12-31 15:19 UTC, isaacvetter commented on input/pagecontent/3_Events.md
> +| [3.2.3 UserLogout.html event](3-2-3-UserLogout.html) |
```suggestion
| [3.2.3 UserLogout.html event](3-2-2-UserLogout.html) |
```

2024-12-31 15:21 UTC, isaacvetter commented on input/pagecontent/4-4-multitab-considerations.md
> +Note that sending a [Home-open event](3-2-5-Home-open.html) merely signals that an application has switched to the no-context tab. It does not change the current context. For instance, if a specific
```suggestion
```

2024-12-31 15:21 UTC, isaacvetter approved these changes

2024-12-31 15:27 UTC, merged